In [1]:
import pandas as pd
import numpy as np

In [2]:
m5_data = pd.read_csv('../Features_New/M5_features_clean.csv')
m5_data.head()

,subid,MMSE,MOCATOTS,CDRSUM,CDRGLOB,MINTTOTS,CRAFTURS,REY1REC,GDS,MOCA_CLOCK_TOTAL
0,3153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3273,1.000000,0.833333,0.000000,0.0,1.0,0.84,0.466667,0.0,0.666667
2,3286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3308,0.866667,NaN,0.027778,1.0,NaN,NaN,NaN,0.0,NaN
4,3315,0.966667,NaN,0.000000,0.0,NaN,NaN,NaN,0.0,NaN

In [3]:
m5_data.describe()

,subid,MMSE,MOCATOTS,CDRSUM,CDRGLOB,MINTTOTS,CRAFTURS,REY1REC,GDS,MOCA_CLOCK_TOTAL
count,1192.000000,269.000000,398.000000,539.000000,539.000000,398.000000,400.000000,32.000000,537.000000,400.000000
mean,8072.976510,0.934944,0.835511,0.034684,0.352505,0.928863,0.619000,0.337500,0.167598,0.859167
std,2261.585665,0.075540,0.129395,0.063423,0.500973,0.081791,0.197972,0.158792,0.450779,0.205465
min,3153.000000,0.633333,0.233333,0.000000,0.000000,0.250000,0.000000,0.066667,0.000000,0.000000
25%,6316.750000,0.900000,0.775000,0.000000,0.000000,0.906250,0.520000,0.250000,0.000000,0.666667
50%,8090.500000,0.966667,0.866667,0.000000,0.000000,0.937500,0.640000,0.333333,0.000000,1.000000
75%,10302.250000,1.000000,0.933333,0.027778,1.000000,1.000000,0.760000,0.400000,0.000000,1.000000
max,10682.000000,1.000000,1.000000,0.444444,2.000000,1.000000,1.000000,0.866667,3.000000,1.000000

In [ ]:
columns_to_scale = ['CDRGLOB', 'GDS']
for col in columns_to_scale:
    max = m5_data[col].max()
    min = m5_data[col].min()
    m5_data[col] = (m5_data[col] - min) / (max - min)

m5_data.to_csv('../Features_New/M5_features_scaled.csv', index=False)

In [5]:
m5_data.describe()

,subid,MMSE,MOCATOTS,CDRSUM,CDRGLOB,MINTTOTS,CRAFTURS,REY1REC,GDS,MOCA_CLOCK_TOTAL
count,1192.000000,269.000000,398.000000,539.000000,539.000000,398.000000,400.000000,32.000000,537.000000,400.000000
mean,8072.976510,0.934944,0.835511,0.034684,0.176252,0.928863,0.619000,0.337500,0.055866,0.859167
std,2261.585665,0.075540,0.129395,0.063423,0.250487,0.081791,0.197972,0.158792,0.150260,0.205465
min,3153.000000,0.633333,0.233333,0.000000,0.000000,0.250000,0.000000,0.066667,0.000000,0.000000
25%,6316.750000,0.900000,0.775000,0.000000,0.000000,0.906250,0.520000,0.250000,0.000000,0.666667
50%,8090.500000,0.966667,0.866667,0.000000,0.000000,0.937500,0.640000,0.333333,0.000000,1.000000
75%,10302.250000,1.000000,0.933333,0.027778,0.500000,1.000000,0.760000,0.400000,0.000000,1.000000
max,10682.000000,1.000000,1.000000,0.444444,1.000000,1.000000,1.000000,0.866667,1.000000,1.000000