In [1]:
import pandas as pd
import numpy as np
import os

In [ ]:
# 46,153 from email

In [30]:
temp0 = pd.read_csv('convert/observation.csv')

In [50]:
temp0.person_id.nunique()

46147

In [41]:
temp00 = temp0[~temp0['observation_source_value'].str.match(r'^[A-Za-z\s]+$', na=False)]
temp00.shape

(10151602, 21)

In [51]:
temp00.person_id.nunique()

44235

In [40]:
temp00.observation_source_value.value_counts()

observation_source_value
SMOKING STATUS                          7262425
Marital Status                          7217893
TIDAL VOLUME - Mechanical Ventilator    3707225
Z79.899                                  207679
Z00.00                                   173162
                                         ...
T47.0X6A                                      1
Z97.16                                        1
V58.71                                        1
E940.1                                        1
Y93.14                                        1
Name: count, Length: 4880, dtype: int64

In [10]:
temp1 = pd.read_csv('convert/condition_occurrence.csv')
temp00 = temp0[['person_id','observation_date', 'observation_source_value']]
temp00.columns = ['person_id', 'condition_start_date', 'condition_source_value']

,condition_occurrence_id,person_id,condition_concept_id,condition_start_date,condition_start_datetime,condition_end_date,condition_end_datetime,condition_type_concept_id,condition_status_concept_id,stop_reason,provider_id,visit_occurrence_id,visit_detail_id,condition_source_value,condition_source_concept_id,condition_status_source_value
0,1133795,6994432031,4330445,2018-10-27,2018-10-27,2018-10-27,2018-10-27,32821,0,NaN,6.993552e+09,7090765605,6995221058,R07.81,45587497,present on admission (?)
1,11246306,6993709501,40484532,2021-03-22,2021-03-22,2021-03-22,2021-03-22,32821,0,NaN,6.993550e+09,7124846797,7001881356,K75.81,45533616,present on admission (?)
2,11765610,6990845878,444094,2015-08-20,2015-08-20,2015-08-20,2015-08-20,32823,0,NaN,6.993687e+09,7056717374,6987107082,V22.1,44829618,present on admission (?)
3,10947482,6992202930,4154290,2024-02-27,2024-02-27,2024-03-04,2024-03-04,32827,0,NaN,6.993490e+09,7184518891,7018670339,I48.0,35207784,present on admission (?)
4,9782933,6989874407,81902,2022-12-23,2022-12-23,2022-12-23,2022-12-23,32821,0,NaN,6.993552e+09,7154267543,6988531539,N39.0,35209324,present on admission (?)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21600913,7969041,6993661792,436741,2018-07-26,2018-07-26,NaN,NaN,32827,0,NaN,6.993552e+09,7091893656,7076196855,N94.818,45592160,present on admission (?)
21600914,8507737,6990721111,433435,2019-08-23,2019-08-23,NaN,NaN,32827,0,NaN,6.993273e+09,7097117253,7015745614,D09.9,35206497,present on admission (?)
21600915,7338128,6991304309,435788,2020-04-13,2020-04-13,2020-04-13,2020-04-13,32823,0,NaN,6.993694e+09,7105687407,7018041789,E83.39,45547663,present on admission (?)
21600916,7603932,6993414130,444101,2021-02-08,2021-02-08,NaN,NaN,32827,0,NaN,6.993550e+09,7125475559,7109229201,I11.0,35207669,present on admission (?)
21600917,6791934,6993790929,77670,2020-10-24,2020-10-24,2020-10-24,2020-10-24,32821,0,NaN,6.993364e+09,7113904117,7008918091,R07.9,45534424,present on admission (?)

In [58]:
temp0.person_id.nunique(), temp1.person_id.nunique(), temp00.person_id.nunique()

(46147, 45827, 46147)

In [59]:
temp11 = pd.concat([temp1[['person_id', 'condition_start_date', 'condition_source_value']], temp00])

In [60]:
temp11.person_id.nunique()

46147

In [11]:
temp2 = pd.read_csv('convert/person.csv')
temp2

,person_id,gender_concept_id,year_of_birth,month_of_birth,day_of_birth,birth_datetime,race_concept_id,ethnicity_concept_id,location_id,provider_id,care_site_id,person_source_value,gender_source_value,gender_source_concept_id,race_source_value,race_source_concept_id,ethnicity_source_value,ethnicity_source_concept_id
0,6986700915,8507,1950,5,27,1950-05-27,8527,38003564,1878561,NaN,NaN,NaN,MALE,0,WHITE,0,NOT HISPANIC,0
1,6986701146,8507,1956,10,24,1956-10-24,8527,38003564,6085423,6.993580e+09,NaN,NaN,MALE,0,WHITE,0,NOT HISPANIC,0
2,6986701379,8507,1953,10,13,1953-10-13,8527,38003564,2373769,6.993594e+09,NaN,NaN,MALE,0,WHITE,0,NOT HISPANIC,0
3,6986701612,8532,1965,7,19,1965-07-19,8527,38003564,5397570,6.993607e+09,NaN,NaN,FEMALE,0,WHITE,0,NOT HISPANIC,0
4,6986701922,8507,1932,6,3,1932-06-03,8527,38003564,1440552,6.993625e+09,NaN,NaN,MALE,0,WHITE,0,NOT HISPANIC,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46143,6994826804,8532,1937,12,13,1937-12-13,8516,38003564,3086807,6.993625e+09,NaN,NaN,FEMALE,0,BLACK,0,NOT HISPANIC,0
46144,6994826823,8532,1938,9,6,1938-09-06,8527,38003564,2734047,6.993636e+09,NaN,NaN,FEMALE,0,WHITE,0,NOT HISPANIC,0
46145,6994827162,8532,1937,4,4,1937-04-04,0,38003564,4012568,6.993388e+09,NaN,NaN,FEMALE,0,OTHER,0,NOT HISPANIC,0
46146,6994827196,8532,1992,11,5,1992-11-05,8527,38003564,3454688,6.993625e+09,NaN,NaN,FEMALE,0,WHITE,0,NOT HISPANIC,0
46147,6994827246,8507,1953,8,17,1953-08-17,8527,38003564,6423771,6.993553e+09,2628.0,NaN,MALE,0,WHITE,0,NOT HISPANIC,0

In [61]:
temp2.person_id.nunique()

46148

In [62]:
t = temp2[['person_id', 'birth_datetime']].drop_duplicates('person_id')

In [63]:
# merge diagnosis and demographic info
temp = pd.merge(temp11, t, on='person_id', how='left')

In [64]:
temp.person_id.nunique()

46147

In [65]:
df_agg = temp[['person_id','birth_datetime','condition_start_date', 'condition_source_value']].groupby(['person_id','condition_start_date']).agg(
    {
        'person_id':'first', 
        'condition_start_date':'first',
        'birth_datetime':'first',
        'condition_source_value': list,

    }
)
df_agg.shape

(4863708, 4)

In [66]:
df_agg.person_id.nunique()

46147

In [67]:
"""
mci code dictionary 
"""
mci_list = ["G31.84", "F06.7", "F06.70", "F06.71", "F09", "R41.840", "R41.841", "R41.89", "R41.9"]
mci_list_no_dots = [code.replace('.', '') for code in mci_list]
mci_list9 = ["331.83", "294.9"]
mci_list9_no_dots = [code.replace('.', '') for code in mci_list9]
mci_list = mci_list + mci_list_no_dots + mci_list9 + mci_list9_no_dots

ad_list =  ["G30", "G30.0", "G30.1", "G30.8", "G30.9"]
ad_list_no_dots = [code.replace('.', '') for code in ad_list]
ad_list9 = ['331.0']
ad_list9_no_dots = [code.replace('.', '') for code in ad_list9]
ad_list = ad_list + ad_list_no_dots + ad_list9 + ad_list9_no_dots

not_control_list = [
    "290.0", "290.10", "290.11", "290.12", "290.13", "290.2", "290.21", "290.3", "290.4", "290.40",
    "290.41", "290.42", "290.43", "290.8", "290.9", "291.2", "292.82", "294.0", "294.1", "294.11",
    "294.2", "294.21", "294.8", "331", "331.1", "331.11", "331.19", "331.2", "331.3", "331.4",
    "331.5", "331.6", "331.7", "331.81", "331.82", "331.89", "332", "332.0", "332.1", "348.81",
    "437.0", "437.1", "437.2", "437.3", "437.4", "437.5", "437.6", "437.7", "437.8", "437.9",
    "797", "A81.0", "F00", "F01", "F01.5", "F01.50", "F01.51", "F02", "F02.80", "F02.81",
    "F03", "F03.90", "F03.91", "F04", "F05", "F05.1", "F06.0", "F06.1", "F06.8", "F10.27",
    "F10.6", "F10.97", "F13.27", "F13.97", "F18.17", "F18.27", "F18.97", "F19.17", "F19.27", "F19.97",
    "G13.8", "G20", "G21", "G21.1", "G21.11", "G21.19", "G21.2", "G21.3", "G21.4", "G21.8",
    "G21.9", "G30", "G30.0", "G30.1", "G30.8", "G30.9", "G31.0", "G31.01", "G31.09", "G31.1",
    "G31.2", "G31.8", "G31.83", "G31.85", "G31.89", "G31.9", "G45.4", "G91.0", "G91.1", "G91.2",
    "G93.7", "G93.81", "G94", "I67.1", "I67.2", "I67.3", "I67.4", "I67.5", "I67.6", "I67.7",
    "I67.81", "I67.82", "I67.89", "I67.9", "R41.81", "R54", "294.9", "331.83", "G31.84", "F06.7",
    "F06.71", "F06.70", "F09"
]
not_control_list_no_dots = [code.replace('.', '') for code in not_control_list]

not_control_list = not_control_list + not_control_list_no_dots + mci_list + ad_list

In [68]:
def get_outcome(row):
#     extract each row's outcome for each subject
        value = row.condition_source_value
        mci = 0
        ad = 0
        control = 0
        if len(set(value).intersection(set(mci_list))) != 0:
            mci = 1
        if len(set(value).intersection(set(ad_list))) != 0:
            ad = 1
        if len(set(value).intersection(set(not_control_list))) == 0:
            control = 1
        row['outcome_mci'] = mci
        row['outcome_ad'] = ad
        row['outcome_control'] = control
        return row
    
def return_outcome(df):
    df = df.apply(get_outcome, axis = 1)
    df.condition_start_date = pd.to_datetime(df.condition_start_date)
    df.birth_datetime = pd.to_datetime(df.birth_datetime)
    df = df.sort_values(by ='condition_start_date', ascending = True)
#     each patient time period
    df['time_period'] = np.floor((df.iloc[-1,1] - df.iloc[0,1]).days/365.25)
#     adding index age and oct age
    
#     control
    if (df.outcome_mci.sum() == 0) and (df.outcome_ad.sum() == 0) and (df.outcome_control.sum() == 0):
        df['outcome_sum'] = 'not case/control'
        df['index_age'] = np.floor((pd.to_datetime(df.iloc[0,1]) - pd.to_datetime(df.iloc[0,2])).days / 365.25)
        df['first_diag_date'] = df.iloc[0,1]
        df['first_diag_date(ad)'] = np.nan
        return df.head(1)
    elif (df.outcome_mci.sum() == 0) and (df.outcome_ad.sum() == 0) and (df.outcome_control.sum() != 0):
        df['outcome_sum'] = 'control'
        df['index_age'] = np.floor((pd.to_datetime(df.iloc[0,1]) - pd.to_datetime(df.iloc[0,2])).days / 365.25)
        df['first_diag_date'] = df.iloc[0,1]
        df['first_diag_date(ad)'] = np.nan
        df.outcome_control = 1
        return df.head(1)
#         mci
    elif (df.outcome_mci.sum() != 0) and (df.outcome_ad.sum() == 0):
        df['outcome_sum'] = 'mci'
#         first mci diagnosis index age
        df['index_age'] = np.floor((pd.to_datetime(df[df.outcome_mci == 1].head(1).condition_start_date.values[0]) - pd.to_datetime(df[df.outcome_mci == 1].head(1).birth_datetime.values[0])).days / 365.25)
        df_start = df[df.outcome_mci == 1]
        df_start['first_diag_date'] = df_start.iloc[0,1]
        df_start['first_diag_date(ad)'] = np.nan
        return df_start.head(1)
#     ad
    elif (df.outcome_mci.sum() == 0) and (df.outcome_ad.sum() != 0):
        df['outcome_sum'] = 'ad'
#         first ad diagnosis index age
        df['index_age'] = np.floor((pd.to_datetime(df[df.outcome_ad == 1].head(1).condition_start_date.values[0]) - pd.to_datetime(df[df.outcome_ad == 1].head(1).birth_datetime.values[0])).days / 365.25)
        df_start = df[df.outcome_ad == 1]
        df_start['first_diag_date'] = df_start.iloc[0,1]
        df_start['first_diag_date(ad)'] = np.nan
        return df_start.head(1)
#     ad + mci
    elif (df.outcome_mci.sum() != 0) and (df.outcome_ad.sum() != 0):
#         for the ad_mci, their condition start date is first mci date, index age is ad age
        df['outcome_sum'] = 'mci + ad'
        df['index_age'] = np.floor((pd.to_datetime(df[df.outcome_ad == 1].head(1).condition_start_date.values[0]) - pd.to_datetime(df[df.outcome_ad == 1].head(1).birth_datetime.values[0])).days / 365.25)
        df_ad_date = df[df.outcome_ad == 1].iloc[0,1]
        df_start = df[df.outcome_mci == 1]
        df_start['first_diag_date'] = df_start.iloc[0,1]
        df_start['first_diag_date(ad)'] = df_ad_date
        df_start.outcome_ad = 1
        return df_start.head(1)
    else:
        print('unknown')
        return None

In [69]:
# cannot directly read df_agg since the list format will change
from tqdm import tqdm 
tqdm.pandas()
result = df_agg.reset_index(drop=True).groupby('person_id').progress_apply(return_outcome)
result.reset_index(drop = True, inplace = True)

100%|██████████| 46147/46147 [1:22:04<00:00,  9.37it/s]

In [70]:
result.to_csv('outcome.csv', index=False)

In [71]:
result.outcome_sum.value_counts()

outcome_sum
mci                 33467
ad                   6168
control              4229
mci + ad             2251
not case/control       32
Name: count, dtype: int64